### ISSUE TITLE
添加出错

### ISSUE THREAD

**Issue by Fsyxr** [Ohdmire/nonebot-plugin-playercheck#3]
![image](https://github.com/Ohdmire/nonebot-plugin-playercheck/assets/85301551/39a57c10-6310-4da7-b100-7c7dcec4faa0)
![image](https://github.com/Ohdmire/nonebot-plugin-playercheck/assets/85301551/37d5c19c-fb9f-4ff3-aaaa-228eee1b56cf)
群友自己添加删除操作后在list也会莫名吧我自己添加的弄没了

**Comment by Ohdmire** [comment]
ok，我再去复现一下，我之前json读写的时候bug挺多的

**Comment by Ohdmire** [comment]
改好了，你升级到v1.5.0测试看看。本来我打算修补一下，结果发现了更多bug然后就改了挺多

**Comment by Ohdmire** [comment]
记得删掉原来的/data/playercheck文件夹，重新导入assets.json，存储的数据结构改了

**Comment by Fsyxr** [comment]
好的
